blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discord
    url: https://vuetube.app/discord
    about: Join the Discord server to chat and ask questions (recommended)
  - name: ğŸ’¬ Telegram
    url: https://t.me/vuetube
    about: Join the Telegram group to chat and ask questions
  - name: ğŸŒ VueTube website
    url: https://vuetube.app/
    about: For example, to check FAQ before asking frecuently asked questions (wait... then they won't be frequently asked questions?)
